import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar/Navbar";
import Hero from "./components/hero/Hero";
import SideModal from "./components/modals/SideModal";

import About from "./components/about/About";
import Assets from "./components/assets/Assets";
import ChatBot from "./components/ChatBot";
import Footer from "./components/footer/Footer";


const font = Nunito({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={font.className}>
        {children}
      
        <Navbar />
        <SideModal />
        <Hero />
        <About />
        <Assets />
        <Footer />
        <ChatBot />
      </body>
    </html>
  );
}
